FROM python:3.11-slim

RUN mkdir -p /home/app

RUN groupadd app && useradd -g app app

ENV APP_HOME=/home/app/src
ENV PYTHONPATH=/home/app/src

RUN mkdir -p $APP_HOME
WORKDIR $APP_HOME

COPY requirements.txt $APP_HOME
COPY requirements-dev.txt $APP_HOME
RUN chown -R app:app /home
USER app
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN pip install -r requirements-dev.txt

ENV PATH="/home/app/.local/bin:${PATH}"
